server:
  port: 8060
  forward-headers-strategy: framework

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){blue} %clr([%X{traceId:-},%X{spanId:-}]){cyan} %clr(${LOG_LEVEL_PATTERN:-%5p}) %m%n"

spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials RETAIN_UNIQUE
        - AddResponseHeader=Access-Control-Allow-Origin, "*"
        - AddResponseHeader=Access-Control-Allow-Methods, GET, POST, PUT, DELETE, OPTIONS
        - AddResponseHeader=Access-Control-Allow-Headers, "*"
        - AddResponseHeader=Access-Control-Allow-Credentials, "true"
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventories/**
          filters:
            - RewritePath=/inventories/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  cache:
    disabled: true
  version: '@springdoc.version@'
  swagger-ui:
    urls:
      - name: inventories
        url: /v3/api-docs/inventories
  api-docs:
    version: openapi_3_1

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans