server:
  port: 0
  forward-headers-strategy: framework

eureka:
  client:
    serviceUrl:
      defaultZone: http://discover-service:8061/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){blue} %clr([%X{traceId:-},%X{spanId:-}]){cyan} %clr(${LOG_LEVEL_PATTERN:-%5p}) %m%n"

springdoc:
  packagesToScan: com.indiana.services.inventory

spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://mysql:3307/indiana-db
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  flyway:
    enabled: false
    validate-on-migrate: true
    baseline-on-migrate: true
    baseline-version: 0

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
