# Use root/example as user/password credentials
#version: '3.1'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
    ports:
      - "3306:3306"
    expose:
      - 3307
    # (this is just an example, not intended to be a production configuration)
