config-service:
  image: docker.io/library/config-service:1.2-SNAPSHOT
  ports:
    - "8088:8088"

discovery-service:
  image: docker.io/library/discovery-service:1.2-SNAPSHOT
  ports:
    - "8061:8061"
  depends_on:
    config-service:
      condition: service_started
  links:
    - config-service
  environment:
    SPRING_PROFILES_ACTIVE: docker

inventory-service:
  image: docker.io/library/inventory-service:1.2-SNAPSHOT
  ports:
    - "8080:8080"
  depends_on:
    mysql:
      condition: service_started
    discovery-service:
      condition: service_started
  links:
    - config-service
    - discovery-service
    - zipkin
  environment:
    SPRING_PROFILES_ACTIVE: docker

gateway-service:
  image: docker.io/library/gateway-service:1.2-SNAPSHOT
  ports:
    - "8060:8060"
  depends_on:
    discovery-service:
      condition: service_started
  environment:
    SPRING_PROFILES_ACTIVE: docker
  links:
    - config-service
    - discovery-service
    - inventory-service
    - zipkin